package com.example.agent.agent.contract;

public enum MusicAgentRoute {
    CAPABILITY_INQUIRY,
    OUT_OF_SCOPE,
    SCOPE_CLARIFICATION,
    PROFILE_ANALYSIS,
    RANDOM_PUBLIC_PLAYLIST,
    PLAYLIST_SEARCH,
    ARTIST_LOOKUP,
    QQ_TREND_DISCOVERY,
    MUSIC_DISCOVERY,
    SUPPORTIVE_MUSIC,
    SUPPORT_SAFETY,
    RESULT_PLAYBACK,
    RESULT_NAVIGATION,
    QUEUE_CONTROL,
    RECOMMENDATION_FOLLOW_UP,
    CONVERSATION
}
