package com.example.agent.model.bo;

public enum AgentActionType {
    SHOW_MUSIC_RESULTS,
    SHOW_QQ_PLAYLIST_RESULTS,
    SHOW_QQ_ARTIST_RESULTS,
    SHOW_QQ_CHART_RESULTS,
    SHOW_MUSIC_PROFILE_STORY,
    SHOW_PROACTIVE_SUGGESTIONS,
    SHOW_WORKFLOW_PROGRESS,
    PLAY_TRACK,
    QUEUE_MUSIC_RESULTS
}
